contexts:
    -   window:
            starting: 2021-07-01T00:00:00Z
            ending: 2021-09-01T00:00:00Z
        streams:
            conductivity:
                qartod:
                    climatology_test:
                        suspect_span: [3.4, 5]
                        fail_span:
            temperature:
                qartod:
                    climatology_test:
                        suspect_span: [7, 27]
                        fail_span:
            pressure:
                qartod:
                    climatology_test:
                        suspect_span: [5, 10]
                        fail_span:
